server:
  port: 80
spring:
  application:
    name: client-feign
eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka/
  instance:
      prefer-ip-address: true
      instance-id: client-feign
feign:
  hystrix:
    enabled: true
