spring:
  application:
    name: order-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudmarket?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: jk123456
server:
    port: 8002
eureka:
    client:
      service-url:
        defaultZone: http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka/
    instance:
      prefer-ip-address: true
      instance-id: order-provider2
